# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#

name: PR Lint and Security

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  TF_VERSION: "1.8.4"
  TF_LINT_VERSION: "v0.50.3"
  CHECKOV_VERSION: "3.2.18"

jobs:
  linting:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        uses: reviewdog/action-tflint@v1.18.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: info
          tflint_init: true

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: github_failed_only
          download_external_modules: true
          soft_fail: true
          skip_check: CKV_AWS_*,CKV_GCP_*,CKV_DOCKER_*
          baseline: .checkov.baseline

      - name: Post Checkov PR Comments
        uses: reviewdog/action-suggester@v1
        if: github.event_name == 'pull_request'
        with:
          tool_name: checkov
          fail_on_error: false
          filter_mode: nofilter
          reporter: github-pr-review
          level: warning

      - name: Run Snyk Infrastructure as Code Test
        uses: snyk/actions/iac@v3.1.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
          args: --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload Snyk scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk.sarif
